version: "3"

services:

  #nginx
  nginx:
    image: registry.cn-chengdu.aliyuncs.com/mediabox/docker-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./docker-nginx/conf/nginx.conf:/etc/nginx/nginx.conf"
      - "./docker-nginx/conf/conf.d:/etc/nginx/conf.d"
      - "${nginx_store}/logs:/var/log/nginx"
    container_name: mediabox_nginx
    restart: always


  # User : admin/admin
  filebrowser:
    image: registry.cn-chengdu.aliyuncs.com/mediabox/docker-filebrowser
#    ports:
#      - "80:80"
    volumes:
      - "${store}:/srv"
      - "${filebrowser_store}:/db"
    container_name: mediabox_filebrowser
    restart: always



# ariang
  ariang:
    image: registry.cn-chengdu.aliyuncs.com/mediabox/docker-ariang
    ports:
#      - "80:8000"
      - "6881-6999:6881-6999/udp"
      - "51413:51413"
      - "6800:6800"
      - "6888:8080"
    volumes:
      - "${store}/downloads:/aria2/downloads"
      - "${ariang_store}/conf:/aria2/conf"
    container_name: mediabox_ariang
    restart: always

    
# samba \\ip\share
  samba:
    image: registry.cn-chengdu.aliyuncs.com/mediabox/docker-samba
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      - "445:445/tcp"
    tmpfs:
      - /tmp
    stdin_open: true
    deploy:
      resources:
        limits:
          memory: 512M #限制内存
    tty: true
    volumes:
      - "${store}:/mount"
    container_name: mediabox_samba
    restart: always
    command: '-p'
    environment:
      - TZ=UTC+08
      - NMBD=yes
      - WORKGROUP=WORKGROUP
      - SHARE=share;/mount;yes;no;yes;;

 
# jellyfin
  jellyfin:
    image: registry.cn-chengdu.aliyuncs.com/mediabox/docker-jellyfin
    ports:
#      - "8096:8096/tcp"
      - "8920:8920/tcp"
      - "7359:7359/udp"
      - "1900:1900/udp"
    volumes:
      - ${jellyfin_store}/config:/config
      - ${store}:/media
    container_name: mediabox_jellyfin
    restart: always

