version: "3"

services:

  #nginx
  nginx:
    build:
      context: ./docker-nginx/
      dockerfile: Dockerfile
    image: mediabox_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./docker-nginx/conf/nginx.conf:/etc/nginx/nginx.conf"
      - "./docker-nginx/conf/conf.d:/etc/nginx/conf.d"
      - "${nginx_store}/logs:/var/log/nginx"
    container_name: mediabox_nginx
    restart: always
    links:
      - "filebrowser"
      - "ariang"

  # User : admin/admin
  filebrowser:
    build:
      context: ./docker-filebrowser/
      dockerfile: Dockerfile
    image: mediabox_filebrowser
#    ports:
#      - "80:80"
    volumes:
      - "${store}:/srv"
      - "${filebrowser_store}:/db"
    container_name: mediabox_filebrowser
    restart: always



# 下载工具
  ariang:
    build:
      context: ./docker-ariang/
      dockerfile: Dockerfile
    image: mediabox_ariang
    ports:
#      - "82:80"
      - "6881-6999:6881-6999/udp"
      - "51413:51413"
      - "6800:6800"
      - "6888:8080"
    volumes:
      - "${store}/downloads:/aria2/downloads"
      - "${ariang_store}/conf:/aria2/conf"
    container_name: mediabox_ariang
    restart: always

    
# samba \\ip\share
  samba:
    build:
      context: ./docker-samba/
      dockerfile: Dockerfile
    image: mediabox_samba
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      - "445:445/tcp"
    tmpfs:
      - /tmp
    stdin_open: true
    deploy:
      resources:
        limits:
          memory: 512M #限制内存
    tty: true
    volumes:
      - "${store}:/mount"
    container_name: mediabox_samba
    restart: always
    command: '-p'
    environment:
      - TZ=UTC+08
      - NMBD=yes
      - WORKGROUP=WORKGROUP
      - SHARE=share;/mount;yes;no;yes;;

      
      
# minidlna
  minidlna:
    build:
      context: ./docker-minidlna/
      dockerfile: Dockerfile
    image: mediabox_minidlna
#    network_mode: "host"  # 网络模式设为 host
    environment:
      - MINIDLNA_MEDIA_DIR=/media
      - MINIDLNA_FRIENDLY_NAME=MiniDLNA
      - MINIDLNA_INOTIFY=yes
      - MINIDLNA_NOTIFY_INTERVAL=3
      - MINIDLNA_NETWORK_INTERFACE=eth1
    ports:
      - "1900:1900/udp"
      - "8200:8200/tcp"
    volumes:
      - ${minidlna_store}/cache:/var/lib/minidlna
      - ${store}:/media
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
    container_name: mediabox_minidlna
    restart: always

      
