version: "3"

services:

  #nginx
  nginx:
    build:
      context: ./docker-nginx/
      dockerfile: Dockerfile
    image: mediabox_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "${nginx_store}/logs:/var/log/nginx"
    container_name: mediabox_nginx
    restart: always
    depends_on:
      - filebrowser
      - ariang
      - jellyfin


  # User : admin/admin
  filebrowser:
    build:
      context: ./docker-filebrowser/
      dockerfile: Dockerfile
    image: mediabox_filebrowser
#    ports:
#      - "80:80"
    volumes:
      - "${store}:/srv"
      - "${filebrowser_store}:/db"
    container_name: mediabox_filebrowser
    restart: always



# ariang
  ariang:
    build:
      context: ./docker-ariang/
      dockerfile: Dockerfile
    image: mediabox_ariang
    ports:
#      - "80:8000"
      - "6881-6999:6881-6999/udp"
      - "51413:51413"
      - "6800:6800"
      - "6888:8080"
    volumes:
      - "${store}/downloads:/aria2/downloads"
      - "${ariang_store}/conf:/aria2/conf"
    container_name: mediabox_ariang
    restart: always

     
# jellyfin
  jellyfin:
    build:
      context: ./docker-jellyfin/
      dockerfile: Dockerfile
    image: mediabox_jellyfin
    ports:
#      - "8096:8096/tcp"
      - "8920:8920/tcp"
      - "7359:7359/udp"
      - "1900:1900/udp"
    volumes:
      - ${jellyfin_store}/config:/config
      - ${store}:/media
    container_name: mediabox_jellyfin
    restart: always
    extra_hosts:
      - "api.themoviedb.org:13.224.161.90"
      - "image.tmdb.org:104.16.61.155"
      - "api.themoviedb.org:13.35.67.86"
      - "www.themoviedb.org:54.192.151.79"


# samba \\ip\share
  samba:
    build:
      context: ./docker-samba/
      dockerfile: Dockerfile
    image: mediabox_samba
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      - "445:445/tcp"
    tmpfs:
      - /tmp
    stdin_open: true
    deploy:
      resources:
        limits:
          memory: 512M #限制内存
    tty: true
    volumes:
      - "${store}:/mount"
    container_name: mediabox_samba
    restart: always
    command: '-p'
    environment:
      - USERID=0
      - GROUPID=0    
      - TZ=UTC+08
      - NMBD=yes
      - WORKGROUP=WORKGROUP
      - SHARE=share;/mount;yes;no;yes;;
      - SMB=LANMAN1 #兼容性更好